var GAME_LEVELS = [
  ["                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "  x                                     o o                   xxx                  ",
   "  x                                                           x!!!!! d             ",
   "  x                         xxx    xxxx     xxxxx           xxxx                o  ",
   "  x        xxxx           xx  !!!!!1                   xxxx             d       o  ",
   "  x@  xxxx           o o  x                          xxx               xxxxx    o  ",
   "  xxxxx11!!!!!!!!xxxxxxxxxxxxxx!!!xxxxxxxx!!!!!!!xxxxxxx!!!!!!!!!!!!!xxxxxxxxxxxxx ",
   "                              x!!!x                  x!!!!!x                       ",
   "                              x!!!x                  x!!!!!x                       ",
   "                              x!!!x                  x!!!!!x                       ",
   "                              xxxxx                  xxxxxxx                       ",
   "                                                                                   ",
   "                                                                                   "],
  ["                                                                                                                                                    ",
   " @                                                                                                                                                  ",
   "xx                                                                                                                                                  ",
   "xx                                                                                                                                                  ",
   "xx                                                                                                                                                  ",
   "xx                                                                                                                                                  ",
   "xx                                                         xxxxxx                                                                                   ",
   "xx                                                         x!!!!x                                                                                   ",
   "xx                                                         x!!!!x                                                                                   ",
   "xx                                                         x!!!!x                                                                                   ",
   "xx                                                         x!!!!x                                                                                   ",
   "xx                                                         x vv x                                                                                   ",
   "xx                                                         x    x                                                       vv                          ",
   "xx                                                                                                                            x                     ",
   "xx                                             o    o                                                                         x                     ",
   "xx                                 xxxxx!!!!!!xxxxxxxxx         xxx                                                           x                     ",
   "xx                         o          =     =!!!!!!x  xxxx        x                                                           x                     ",
   "xx                xx     xxx   xxxxx        xxxxxxxx  x           x                   o o                     =  d            x                     ",
   "xx              xx!!!!!!!!                            x        xxxx                 xxxxxx    xxxxx!!!!!xxxxx                 x                     ",
   "xx             xx!!!!!!                               x           x                !!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx        x                     ",
   "xx        o o x!!!!!!!!                               x d         x         xxxxx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx          oo x                     ",
   "xx      xxxxxx!!!!!!!                                 xxxx        x                =!!!!!!!!!!!!!!!!!!!xxxxxxxxxx      xxxxxxxx                     ",
   "xx   xxxx!!!!!!!!x      xx                            x           xxxxxxxx        !!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx                                   ",
   "xx!!!!!!x!!!!!!!!x!!!!!xx                             x        xxxx!!!!!!!!!!!!!!!!!!x                                                              ",
   "xx!!!!!!x!!!!!!!!x!!!!!xx                             x           x!!!!!!!!!!!!!!!!!!x                                                              ",
   "xx!!!!!!x!!!!!!!!x!!!!!xx                             xxxx        x!!!!!!!!!!!!!!!!!!x                                                              ",
   "xx!!!!!!x!!!!!!!!x!!!!!xx                             x           x!!!!!!!!!!!!!!!!!!x                                                              ",
   "xx!!!!!!x!!!!!!!!x!!!!!xx                             x d      xxxx!!!!!!!!!!!!!!!!!!x                                                              ",
   "xx!!!!!x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!xxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!x                                                              ",
   "           !                                                                                                                                        "],
  ["                                                                                                                   ",
   "         v      v         v        v      v          v        v          v       v       v        v                ",
   "                                                                                                                   ",
   "   @                                                                                                               ",
   "xxxxxx                                                                                                             ",
   "          xxxxxxxx                                                                    =                                               ",
   "                                 xxxxxxx                           xx                                                                 ",
   "                                                                                   xxx      xxx         xxx                           ",
   "   xxxxxx              xxxxxx                 xxxxxxxx          =                                                                     ",
   "                =                   v                                       xx                                                        ",
   "                                                                                                      xxxx                            ",
   "                                                             xxxx                        =                                            ",
   "        xxxxxxxxxx             xxxxxxxxx            xxxx            =                    v         xxxx                               ",
   "                                                                            xxx                                                       ",
   "                  v                                         =                                       xxxx                              ",
   "                         xxxxxxxx                               xxxxxxx                                                               ",
   "                                       xxxxxxx    v                                    xxxx                                           ",
   "               xxxxxxxxx     v     =                  =                                                                               ",
   "              v                                              xx           xxxxxx         xx   =                                       ",
   "                                                        v                                                                             ",
   "                            xxxxx        xxxxxxxxxx               xxxxxxxx                                                            ",
   "            xxxxxxx                                                                 xxx                                               ",
   "                                                     xxxxxxx                                                                          ",
   "                                         xxx                                                                                          ",
   "                 xxxxxxxx         =                           xxxxxx                      =                                           ",
   "                                                 =       v                         =           xxxxxxxx                               ",
   "                                                                        xxxxx                                                         ",
   "                                             v                                                                                        ", 
   "      v       v                                                                                                                       ",
   "                   xxxxxx                   xxx                                   xxxx    xxxxxx                                      ",
   "                                 =              xxx                 =                                                                 ",
   "                                                                                               =                                      ",
   "         xx                         v                                                  xxxx                                           ",
   "                                          v                   v                                                                       ",
   "                    v            xxxx               xxxx               xxxx                     xxxxxxx                               ",
   "           xxxxx                                               =                             x                 x                      ",
   "                                                                                             x                 x                      ",
   "                 xxxxx                xxxxx                                                  x                 x                      ",
   "                                                                        xxxxxxx              x                 x                      ",
   "                                                                                             xdodododoododododox                      ",
   "                                                                                             xdodododoododododox                      ",
   "       xxx                                                                                   xxxxxxxxxxxxxxxxxxx                      ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                        ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                        ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                        ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                        "],
  ["                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "               x                                                  x                                                             ",
   "                x                                                x                                                              ",
   "                 x                                              x                                                               ",
   "                  x                                            x                                                                ",
   "                   x                       xxx                x                                                                 ",
   "                    x                    x    x              x                                                                  ",
   "                     x                 x       x            x                                                                   ",
   "                      x              x          x          x                                                                    ",
   "                       x           x             x        x                                                                     ",
   "                        x        x                x      x                                                                      ",
   "                         x     x                   x    x                                                                       ",
   "                          x  x                      x  x                                                                        ",
   "                           x                         x                                                                          ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                ",
   "                                                                                                                                "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
